# Generated by Django 3.2.5 on 2021-07-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
