# Generated by Django 3.2.5 on 2021-08-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, default=None, upload_to='uploads/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosyapp.project')),
            ],
        ),
    ]
