# Generated by Django 3.2.5 on 2021-08-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosyapp', '0002_referencephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencephoto',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
