# Generated by Django 3.2.5 on 2021-07-29 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosyapp', '0003_part_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosyapp.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosyapp.part'),
        ),
        migrations.CreateModel(
            name='ToBuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField()),
                ('completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosyapp.project')),
            ],
        ),
    ]
