# Generated by Django 3.2.5 on 2021-08-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosyapp', '0006_alter_tobuyitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
